server:
  port: '9003'
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/order'
    username: kalpamadmin
    password: Kalpam@321
  jpa:
    properties:
      hibernate:
        default_schema: kalpam
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  main:
    allow-circular-references: true
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'